-- GENERATED by scripts/generate-official-seed.cjs from assets/js/official-data.js. DO NOT EDIT.
-- Deterministic and idempotent official Test seed: 12 teams, 60 matches, 26 results; 26 final, 34 scheduled.

begin;
insert into public.seasons(code,name,status,start_date,end_date) values('2026-autumn-second-half','2026 烏日桌球聯賽（下半季）','active','2026-08-23'::date,'2026-12-06'::date) on conflict(code) do update set name=excluded.name,status=excluded.status,start_date=excluded.start_date,end_date=excluded.end_date;
insert into public.groups(season_id,code,name,display_order) select s.id,v.code,v.name,v.ord from public.seasons s cross join (values ('A','A 組',1),('B','B 組',2)) v(code,name,ord) where s.code='2026-autumn-second-half' on conflict(season_id,code) do update set name=excluded.name,display_order=excluded.display_order;

insert into public.teams(team_code,name,short_name,description,logo_path,active) values
  ('A01','快樂Da桌球','快樂Da桌球','',''),
  ('A02','夢幻羽翼','夢幻羽翼','',''),
  ('A03','好球隊','好球隊','',''),
  ('A04','小三美日','小三美日','',''),
  ('A05','叔叔沒練球','叔叔沒練球','',''),
  ('A06','陽光男孩','陽光男孩','',''),
  ('B01','我們這一隊','我們這一隊','',''),
  ('B02','劉家昌','劉家昌','',''),
  ('B03','烏日少年','烏日少年','',''),
  ('B04','海納百川','海納百川','',''),
  ('B05','南門金龍','南門金龍','',''),
  ('B06','富士山','富士山','','')
on conflict(team_code) do update set name=excluded.name,short_name=excluded.short_name,description=excluded.description,logo_path=excluded.logo_path,active=true,updated_at=now();

with v(team_code,group_code,display_order) as (values
  ('A01','A','1'),
  ('A02','A','2'),
  ('A03','A','3'),
  ('A04','A','4'),
  ('A05','A','5'),
  ('A06','A','6'),
  ('B01','B','1'),
  ('B02','B','2'),
  ('B03','B','3'),
  ('B04','B','4'),
  ('B05','B','5'),
  ('B06','B','6')
) insert into public.season_teams(season_id,team_id,group_id,display_name,display_order,active) select s.id,t.id,g.id,'',v.display_order::integer,true from v join public.seasons s on s.code='2026-autumn-second-half' join public.teams t on t.team_code=v.team_code join public.groups g on g.season_id=s.id and g.code=v.group_code on conflict(season_id,team_id) do update set group_id=excluded.group_id,display_name=excluded.display_name,display_order=excluded.display_order,active=true;

do $$ begin
  if exists(select 1 from public.matches m join public.seasons s on s.id=m.season_id where m.match_code in ('A-2026-08-23-1','A-2026-08-23-2','A-2026-08-23-3','A-2026-08-23-4','A-2026-08-23-5','A-2026-08-23-6','A-2026-09-06-1','A-2026-09-06-2','A-2026-09-06-3','A-2026-09-06-4','A-2026-09-06-5','A-2026-09-20-1','A-2026-09-20-2','A-2026-09-20-3','A-2026-09-20-4','A-2026-10-18-1','A-2026-10-18-2','A-2026-10-18-3','A-2026-10-18-4','A-2026-10-18-5','A-2026-10-18-6','A-2026-11-08-1','A-2026-11-08-2','A-2026-11-08-3','A-2026-11-08-4','A-2026-11-08-5','A-2026-11-22-1','A-2026-11-22-2','A-2026-11-22-3','A-2026-11-22-4','B-2026-08-30-1','B-2026-08-30-2','B-2026-08-30-3','B-2026-08-30-4','B-2026-08-30-5','B-2026-08-30-6','B-2026-09-13-1','B-2026-09-13-2','B-2026-09-13-3','B-2026-09-13-4','B-2026-09-13-5','B-2026-10-04-1','B-2026-10-04-2','B-2026-10-04-3','B-2026-10-04-4','B-2026-11-01-1','B-2026-11-01-2','B-2026-11-01-3','B-2026-11-01-4','B-2026-11-01-5','B-2026-11-01-6','B-2026-11-15-1','B-2026-11-15-2','B-2026-11-15-3','B-2026-11-15-4','B-2026-11-15-5','B-2026-11-29-1','B-2026-11-29-2','B-2026-11-29-3','B-2026-11-29-4') and s.code<>'2026-autumn-second-half') then
    raise exception 'official seed match_code belongs to another season';
  end if;
end $$;

with v(match_code,group_code,match_date,match_time,home_code,away_code,venue,status) as (values
  ('A-2026-08-23-1','A','2026-08-23','15:30','A01','A02','','final'),
  ('A-2026-08-23-2','A','2026-08-23','15:30','A03','A04','','final'),
  ('A-2026-08-23-3','A','2026-08-23','16:00','A01','A03','','final'),
  ('A-2026-08-23-4','A','2026-08-23','16:00','A02','A04','','final'),
  ('A-2026-08-23-5','A','2026-08-23','16:30','A01','A04','','final'),
  ('A-2026-08-23-6','A','2026-08-23','16:30','A02','A03','','final'),
  ('A-2026-09-06-1','A','2026-09-06','15:30','A03','A05','','final'),
  ('A-2026-09-06-2','A','2026-09-06','15:30','A04','A06','','final'),
  ('A-2026-09-06-3','A','2026-09-06','16:00','A03','A06','','final'),
  ('A-2026-09-06-4','A','2026-09-06','16:00','A04','A05','','final'),
  ('A-2026-09-06-5','A','2026-09-06','16:30','A05','A06','','final'),
  ('A-2026-09-20-1','A','2026-09-20','15:30','A01','A05','','final'),
  ('A-2026-09-20-2','A','2026-09-20','15:30','A02','A06','','final'),
  ('A-2026-09-20-3','A','2026-09-20','16:00','A01','A06','','final'),
  ('A-2026-09-20-4','A','2026-09-20','16:00','A02','A05','','final'),
  ('A-2026-10-18-1','A','2026-10-18','15:30','A01','A02','','scheduled'),
  ('A-2026-10-18-2','A','2026-10-18','15:30','A03','A04','','scheduled'),
  ('A-2026-10-18-3','A','2026-10-18','16:00','A01','A03','','scheduled'),
  ('A-2026-10-18-4','A','2026-10-18','16:00','A02','A04','','scheduled'),
  ('A-2026-10-18-5','A','2026-10-18','16:30','A01','A04','','scheduled'),
  ('A-2026-10-18-6','A','2026-10-18','16:30','A02','A03','','scheduled'),
  ('A-2026-11-08-1','A','2026-11-08','15:30','A03','A05','','scheduled'),
  ('A-2026-11-08-2','A','2026-11-08','15:30','A04','A06','','scheduled'),
  ('A-2026-11-08-3','A','2026-11-08','16:00','A03','A06','','scheduled'),
  ('A-2026-11-08-4','A','2026-11-08','16:00','A04','A05','','scheduled'),
  ('A-2026-11-08-5','A','2026-11-08','16:30','A05','A06','','scheduled'),
  ('A-2026-11-22-1','A','2026-11-22','15:30','A01','A05','','scheduled'),
  ('A-2026-11-22-2','A','2026-11-22','15:30','A02','A06','','scheduled'),
  ('A-2026-11-22-3','A','2026-11-22','16:00','A01','A06','','scheduled'),
  ('A-2026-11-22-4','A','2026-11-22','16:00','A02','A05','','scheduled'),
  ('B-2026-08-30-1','B','2026-08-30','15:30','B01','B02','','final'),
  ('B-2026-08-30-2','B','2026-08-30','15:30','B03','B04','','final'),
  ('B-2026-08-30-3','B','2026-08-30','16:00','B01','B03','','final'),
  ('B-2026-08-30-4','B','2026-08-30','16:00','B02','B04','','final'),
  ('B-2026-08-30-5','B','2026-08-30','16:30','B01','B04','','final'),
  ('B-2026-08-30-6','B','2026-08-30','16:30','B02','B03','','final'),
  ('B-2026-09-13-1','B','2026-09-13','15:30','B03','B05','','final'),
  ('B-2026-09-13-2','B','2026-09-13','15:30','B04','B06','','final'),
  ('B-2026-09-13-3','B','2026-09-13','16:00','B03','B06','','final'),
  ('B-2026-09-13-4','B','2026-09-13','16:00','B04','B05','','final'),
  ('B-2026-09-13-5','B','2026-09-13','16:30','B05','B06','','final'),
  ('B-2026-10-04-1','B','2026-10-04','15:30','B01','B05','','scheduled'),
  ('B-2026-10-04-2','B','2026-10-04','15:30','B02','B06','','scheduled'),
  ('B-2026-10-04-3','B','2026-10-04','16:00','B01','B06','','scheduled'),
  ('B-2026-10-04-4','B','2026-10-04','16:00','B02','B05','','scheduled'),
  ('B-2026-11-01-1','B','2026-11-01','15:30','B01','B02','','scheduled'),
  ('B-2026-11-01-2','B','2026-11-01','15:30','B03','B04','','scheduled'),
  ('B-2026-11-01-3','B','2026-11-01','16:00','B01','B03','','scheduled'),
  ('B-2026-11-01-4','B','2026-11-01','16:00','B02','B04','','scheduled'),
  ('B-2026-11-01-5','B','2026-11-01','16:30','B01','B04','','scheduled'),
  ('B-2026-11-01-6','B','2026-11-01','16:30','B02','B03','','scheduled'),
  ('B-2026-11-15-1','B','2026-11-15','15:30','B03','B05','','scheduled'),
  ('B-2026-11-15-2','B','2026-11-15','15:30','B04','B06','','scheduled'),
  ('B-2026-11-15-3','B','2026-11-15','16:00','B03','B06','','scheduled'),
  ('B-2026-11-15-4','B','2026-11-15','16:00','B04','B05','','scheduled'),
  ('B-2026-11-15-5','B','2026-11-15','16:30','B05','B06','','scheduled'),
  ('B-2026-11-29-1','B','2026-11-29','15:30','B01','B05','','scheduled'),
  ('B-2026-11-29-2','B','2026-11-29','15:30','B02','B06','','scheduled'),
  ('B-2026-11-29-3','B','2026-11-29','16:00','B01','B06','','scheduled'),
  ('B-2026-11-29-4','B','2026-11-29','16:00','B02','B05','','scheduled')
) insert into public.matches(season_id,group_id,match_code,match_date,match_time,home_team_id,away_team_id,venue,status,published,locked) select s.id,g.id,v.match_code,v.match_date::date,v.match_time::time,ht.id,at.id,v.venue,v.status,true,false from v join public.seasons s on s.code='2026-autumn-second-half' join public.groups g on g.season_id=s.id and g.code=v.group_code join public.teams ht on ht.team_code=v.home_code join public.teams at on at.team_code=v.away_code on conflict(match_code) do update set group_id=excluded.group_id,match_date=excluded.match_date,match_time=excluded.match_time,home_team_id=excluded.home_team_id,away_team_id=excluded.away_team_id,venue=excluded.venue,status=excluded.status,published=true where public.matches.season_id=excluded.season_id;

do $$ begin
  if exists(select 1 from public.matches m join public.seasons s on s.id=m.season_id where m.match_code in ('A-2026-08-23-1','A-2026-08-23-2','A-2026-08-23-3','A-2026-08-23-4','A-2026-08-23-5','A-2026-08-23-6','A-2026-09-06-1','A-2026-09-06-2','A-2026-09-06-3','A-2026-09-06-4','A-2026-09-06-5','A-2026-09-20-1','A-2026-09-20-2','A-2026-09-20-3','A-2026-09-20-4','A-2026-10-18-1','A-2026-10-18-2','A-2026-10-18-3','A-2026-10-18-4','A-2026-10-18-5','A-2026-10-18-6','A-2026-11-08-1','A-2026-11-08-2','A-2026-11-08-3','A-2026-11-08-4','A-2026-11-08-5','A-2026-11-22-1','A-2026-11-22-2','A-2026-11-22-3','A-2026-11-22-4','B-2026-08-30-1','B-2026-08-30-2','B-2026-08-30-3','B-2026-08-30-4','B-2026-08-30-5','B-2026-08-30-6','B-2026-09-13-1','B-2026-09-13-2','B-2026-09-13-3','B-2026-09-13-4','B-2026-09-13-5','B-2026-10-04-1','B-2026-10-04-2','B-2026-10-04-3','B-2026-10-04-4','B-2026-11-01-1','B-2026-11-01-2','B-2026-11-01-3','B-2026-11-01-4','B-2026-11-01-5','B-2026-11-01-6','B-2026-11-15-1','B-2026-11-15-2','B-2026-11-15-3','B-2026-11-15-4','B-2026-11-15-5','B-2026-11-29-1','B-2026-11-29-2','B-2026-11-29-3','B-2026-11-29-4') and s.code<>'2026-autumn-second-half') then
    raise exception 'official seed match_code belongs to another season';
  end if;
end $$;

with v(match_code,home_score,away_score,note) as (values
  ('A-2026-08-23-1',3,0,'正式賽果'),
  ('A-2026-08-23-2',2,1,'正式賽果'),
  ('A-2026-08-23-3',0,3,'正式賽果'),
  ('A-2026-08-23-4',1,2,'正式賽果'),
  ('A-2026-08-23-5',1,2,'正式賽果'),
  ('A-2026-08-23-6',0,3,'正式賽果'),
  ('A-2026-09-06-1',0,3,'正式賽果'),
  ('A-2026-09-06-2',3,0,'正式賽果'),
  ('A-2026-09-06-3',3,0,'正式賽果'),
  ('A-2026-09-06-4',0,3,'正式賽果'),
  ('A-2026-09-06-5',3,0,'正式賽果'),
  ('A-2026-09-20-1',0,3,'正式賽果'),
  ('A-2026-09-20-2',0,3,'正式賽果'),
  ('A-2026-09-20-3',0,3,'正式賽果'),
  ('A-2026-09-20-4',0,3,'正式賽果'),
  ('B-2026-08-30-1',0,3,'正式賽果'),
  ('B-2026-08-30-2',3,0,'正式賽果'),
  ('B-2026-08-30-3',3,0,'正式賽果'),
  ('B-2026-08-30-4',3,0,'正式賽果'),
  ('B-2026-08-30-5',1,2,'正式賽果'),
  ('B-2026-08-30-6',3,0,'正式賽果'),
  ('B-2026-09-13-1',3,0,'正式賽果'),
  ('B-2026-09-13-2',0,3,'正式賽果'),
  ('B-2026-09-13-3',1,2,'正式賽果'),
  ('B-2026-09-13-4',2,1,'正式賽果'),
  ('B-2026-09-13-5',0,3,'正式賽果')
) insert into public.match_results(match_id,home_score,away_score,note,published,locked) select m.id,v.home_score::integer,v.away_score::integer,v.note,true,true from v join public.matches m on m.match_code=v.match_code join public.seasons s on s.id=m.season_id and s.code='2026-autumn-second-half' on conflict(match_id) do update set home_score=excluded.home_score,away_score=excluded.away_score,note=excluded.note,published=true,locked=true,updated_at=now();

update public.matches m set status='final' from public.seasons s where m.season_id=s.id and s.code='2026-autumn-second-half' and m.match_code in ('A-2026-08-23-1','A-2026-08-23-2','A-2026-08-23-3','A-2026-08-23-4','A-2026-08-23-5','A-2026-08-23-6','A-2026-09-06-1','A-2026-09-06-2','A-2026-09-06-3','A-2026-09-06-4','A-2026-09-06-5','A-2026-09-20-1','A-2026-09-20-2','A-2026-09-20-3','A-2026-09-20-4','B-2026-08-30-1','B-2026-08-30-2','B-2026-08-30-3','B-2026-08-30-4','B-2026-08-30-5','B-2026-08-30-6','B-2026-09-13-1','B-2026-09-13-2','B-2026-09-13-3','B-2026-09-13-4','B-2026-09-13-5') and m.status is distinct from 'final';

with v(group_code,snapshot_date,team_code,points,wins,losses,rank,rank_change) as (values
  ('A','2026-09-20','A05',15,5,0,1,1),
  ('A','2026-09-20','A03',11,4,1,2,-1),
  ('A','2026-09-20','A04',8,3,2,3,0),
  ('A','2026-09-20','A06',6,2,3,4,2),
  ('A','2026-09-20','A01',4,1,4,5,-1),
  ('A','2026-09-20','A02',1,0,5,6,-1),
  ('B','2026-09-13','B02',9,3,0,1,0),
  ('B','2026-09-13','B06',8,3,0,2,0),
  ('B','2026-09-13','B03',7,2,3,3,0),
  ('B','2026-09-13','B04',4,2,3,4,0),
  ('B','2026-09-13','B01',4,1,2,5,-3),
  ('B','2026-09-13','B05',1,0,3,6,0)
) insert into public.standings_snapshots(season_id,group_id,team_id,snapshot_date,points,wins,losses,rank,rank_change) select s.id,g.id,t.id,v.snapshot_date::date,v.points::integer,v.wins::integer,v.losses::integer,v.rank::integer,v.rank_change::integer from v join public.seasons s on s.code='2026-autumn-second-half' join public.groups g on g.season_id=s.id and g.code=v.group_code join public.teams t on t.team_code=v.team_code on conflict(season_id,group_id,team_id,snapshot_date) do update set points=excluded.points,wins=excluded.wins,losses=excluded.losses,rank=excluded.rank,rank_change=excluded.rank_change;
commit;
