'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs');
const R=require('../assets/js/reporting-core.js');
test('review classification is exhaustive and completion is independent of lock/publication/report conflicts',()=>{
 assert.equal(R.reviewState(null,false),'missing');assert.equal(R.reviewState(null,true),'reported');for(const result of [{locked:false,published:false},{locked:true,published:false},{locked:false,published:true}])for(const hasReports of [false,true])assert.equal(R.reviewState(result,hasReports),'final');assert.deepEqual(R.reviewLabels,{reported:'核對',missing:'補登',final:'完成'});
});
test('report input rejects blank and illegal scores',()=>{for(const pair of [['','3'],['3',''],['3','1'],['1','1']])assert.equal(R.valid(...pair),false);for(const pair of [['3','0'],['0','3'],['2','1'],['1','2']])assert.equal(R.valid(...pair),true)});
test('single report is selected, conflicting reports are never auto-selected',()=>{assert.equal(R.draft(null,[{id:'r',home_score:3,away_score:0}]).source,'r');assert.equal(R.draft(null,[{id:'r',home_score:3,away_score:0},{id:'s',home_score:2,away_score:1}]).source,'');assert.equal(R.draft({home_score:1,away_score:2,version:5},[]).source,'custom')});
test('uncertain writes are frozen until exact receipt reconciliation; repeat writes blocked',async()=>{let writes=0;const s=new R.RequestState(()=> 'request-1');const payload={match_code:'M1',home_score:3,away_score:0};await assert.rejects(s.send(payload,async()=>{writes++;throw Error('network')}));assert.equal(s.phase,'unknown');await assert.rejects(s.send(payload,async()=>writes++));assert.equal(writes,1);assert.throws(()=>s.resolve({status:'received',match_code:'M2',request_id:'request-1'}));s.resolve({status:'received',match_code:'M1',request_id:'request-1'});assert.equal(s.phase,'saved')});
test('definite rejection preserves draft and allows a new request; pending double clicks blocked',async()=>{const s=new R.RequestState(()=> 'request-1');let finish;const p=s.send({match_code:'M1'},()=>new Promise(resolve=>finish=resolve));await assert.rejects(s.send({},()=>{}));finish({match_code:'M1',request_id:'request-1'});await p;const rejected=new R.RequestState(()=> 'request-2');await assert.rejects(rejected.send({match_code:'M2'},()=>{const e=Error('denied');e.mutationState='rejected';throw e}));assert.equal(rejected.phase,'rejected');assert.equal(rejected.payload.match_code,'M2')});
test('all request receipts require matching request and match',async()=>{const s=new R.RequestState(()=> 'r1');await assert.rejects(s.send({match_code:'M'},async()=>({match_code:'M',request_id:'r2'})));assert.equal(s.phase,'unknown');s.resolve({status:'not_received',match_code:'M',request_id:'r1'});assert.equal(s.phase,'rejected')});
test('daily backend guards are fail closed, scoped, serialized and transactional',()=>{const sql=fs.readFileSync('supabase/migrations/014_daily_score_reporting.sql','utf8');assert.match(sql,/season_id=link.season_id and match_date=link.match_date/g);assert.match(sql,/role_name is null or role_name not in/);assert.match(sql,/is distinct from 'admin'/);assert.match(sql,/for update/);assert.match(sql,/request identity conflict/);assert.match(sql,/p_expected_version is null/);assert.match(sql,/referee_report_requests/);assert.match(sql,/revoke all on public.daily_report_links/)});
