const test=require('node:test'),assert=require('node:assert/strict');
function harness(api){const {create}=require('../assets/js/publication-ui.js'),elements=new Map(),timers=new Map();let next=0;const el=id=>{if(!elements.has(id))elements.set(id,{textContent:'',disabled:false,hidden:false,open:false,showModal(){this.open=true},close(){this.open=false;this.onclose?.()},addEventListener(name,fn){this['on'+name]=fn},focus(){}});return elements.get(id)};const document={getElementById:el,visibilityState:'visible',addEventListener(){}};const ui=create({document,authorized:()=>true,call:api,openDialog:d=>d.showModal(),setTimer:fn=>{timers.set(++next,fn);return next},clearTimer:id=>timers.delete(id)});return {ui,el,timers};}
const synced={status:'synced',can_publish:false,last_published_at:'2026-10-04T03:02:28Z',automatic_enabled:true,automatic_interval_seconds:120};
test('unknown and unchanged states disable publication; only authoritative dirty state enables',async()=>{const {summaryView}=require('../assets/js/publication-ui.js');for(const state of [null,synced,{status:'queued',can_publish:true},{status:'dirty',can_publish:false}])assert.equal(summaryView(state).enabled,false);assert.equal(summaryView({status:'dirty',can_publish:true}).enabled,true)});
test('opening synced dialog performs one small state read, no background polling or publish',async()=>{const calls=[];const h=harness(async action=>{calls.push(action);return synced});await h.ui.open();assert.deepEqual(calls,['state']);assert.equal(h.el('publishSnapshot').disabled,true);assert.equal(h.timers.size,0);assert.match(h.el('publicationStatus').textContent,/已同步/)});
test('publish rechecks dirty state and never dispatches if another administrator already published',async()=>{let n=0;const calls=[];const h=harness(async action=>{calls.push(action);return ++n===1?{status:'dirty',can_publish:true}:synced});await h.ui.open();await h.ui.publish();assert.deepEqual(calls,['state','state']);assert.equal(h.el('publishSnapshot').disabled,true)});
test('only exact current request is tracked; online result and history are separate; completion stops polling',async()=>{const calls=[];let done=false;const id='12345678-1234-1234-1234-123456789abc';const h=harness(async(action,requestId)=>{calls.push([action,requestId]);if(action==='state')return done?synced:{status:'dirty',can_publish:true};if(action==='publish')return {status:'queued',request_id:id};assert.equal(requestId,id);done=true;return {status:'published',request_id:id,published_at:synced.last_published_at}});await h.ui.open();await h.ui.publish();assert.match(h.el('publicationTask').textContent,/尚未更新/);assert.equal(h.timers.size,1);await h.ui.check();assert.match(h.el('publicationTask').textContent,/已確認上線/);assert.match(h.el('publicationHistory').textContent,/上次/);assert.equal(h.timers.size,0);assert.equal(h.el('publishSnapshot').disabled,true)});
test('read failure stops tracking, disables publish, preserves request and supports explicit check',async()=>{let fail=false;const id='12345678-1234-1234-1234-123456789abc';const h=harness(async(action,rid)=>{if(fail)throw new Error('unavailable');if(action==='state')return {status:'queued',pending_request_id:id,can_publish:false};assert.equal(rid,id);return {status:'dispatch_unknown',request_id:id}});await h.ui.open();fail=true;await h.ui.check();assert.equal(h.timers.size,0);assert.equal(h.el('publishSnapshot').disabled,true);assert.match(h.el('publicationTask').textContent,/不可重送/);fail=false;await h.ui.check();assert.match(h.el('publicationTask').textContent,/觸發結果待確認/)});
test('closing dialog stops timers; stale in-flight state cannot enable button after invalidate',async()=>{let release;const h=harness(async()=>new Promise(resolve=>release=resolve));const p=h.ui.open();h.ui.invalidate();release({status:'dirty',can_publish:true});await p;assert.equal(h.el('publishSnapshot').disabled,true);h.el('publicationDialog').close();assert.equal(h.timers.size,0)});
test('unknown publish outcome cannot be cleared by a superficially synced summary',async()=>{let first=true;const h=harness(async action=>{if(action==='publish')throw new Error('network');if(first){return {status:'dirty',can_publish:true}}return synced});await h.ui.open();await h.ui.publish();first=false;await h.ui.check();assert.equal(h.el('publishSnapshot').disabled,true);assert.match(h.el('publicationTask').textContent,/不可重送/)});

test('direct publication completes in the click response, shows published and does not start a polling timer',async()=>{let published=false;const id='12345678-1234-1234-1234-123456789abc';const calls=[];const h=harness(async action=>{calls.push(action);if(action==='publish'){published=true;return {status:'published',request_id:id,published_at:synced.last_published_at,delivery_method:'storage'}}return published?{...synced,delivery_method:'storage'}:{status:'dirty',can_publish:true,delivery_method:'storage'}});await h.ui.open();await h.ui.publish();assert.match(h.el('publicationTask').textContent,/已確認上線/);assert.equal(h.timers.size,0);assert.equal(h.el('publishSnapshot').disabled,true);assert(!calls.includes('status'))});

test('a confirmed direct publish stays successful when the subsequent summary refresh fails',async()=>{let done=false;const h=harness(async action=>{if(action==='publish'){done=true;return {status:'published',request_id:'12345678-1234-1234-1234-123456789abc',published_at:synced.last_published_at}}if(done)throw new Error('summary unavailable');return {status:'dirty',can_publish:true}});await h.ui.open();await h.ui.publish();assert.match(h.el('publicationTask').textContent,/已確認上線/);assert.equal(h.el('publishSnapshot').disabled,true);assert.equal(h.timers.size,0)});
test('mismatched status receipt cannot claim online success',async()=>{const h=harness(async action=>action==='state'?{status:'queued',can_publish:false,pending_request_id:'12345678-1234-1234-1234-123456789abc'}:{status:'published',request_id:'22345678-1234-1234-1234-123456789abc'});await h.ui.open();await h.ui.check();assert(!h.el('publicationTask').textContent.includes('已確認上線'));assert.equal(h.el('publishSnapshot').disabled,true)});
