const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs');
const id='12345678-1234-1234-1234-123456789abc';
const request=(body={action:'state'})=>new Request('https://test',{method:'POST',headers:{Origin:'https://bollinmore-hermes.github.io',Authorization:'Bearer placeholder'},body:JSON.stringify(body)});
function deps(summary,role='admin'){return {environment:'test',supabaseUrl:'https://vppjcjfbcoxzofcuxmzz.supabase.co',githubToken:'server-only-placeholder',userClient:{auth:{getUser:async()=>({data:{user:{id}},error:null})}},serviceClient:{from:()=>({select:()=>({eq:()=>({maybeSingle:async()=>({data:{role,active:true},error:null})})})}),rpc:async(name)=>{assert.equal(name,'get_publication_status_summary');return {data:summary,error:null}}},fetcher:async()=>assert.fail('summary must not fetch GitHub, Pages or public data')};}
const base={verified_hash_known:true,needs_publish:false,pending_request_id:null,pending_status:null,cooldown_until:null,last_published_at:'2026-10-04T03:02:28Z',automatic_enabled:true,interval_seconds:120};
test('state command is admin-only, target-free and cannot accept request IDs',async()=>{const {handlePublication,parseCommand}=await import('../supabase/functions/publish-public-snapshot/core.mjs');assert.deepEqual(parseCommand({action:'state'}),{action:'state'});for(const value of [{action:'state',request_id:id},{action:'state',season:'other'},{action:'state',repo:'other'}])assert.throws(()=>parseCommand(value));assert.equal((await handlePublication(request(),deps(base,'scorer'))).status,403)});
test('unchanged state is small, read-only, disables manual publish and exposes no hashes',async()=>{const {handlePublication}=await import('../supabase/functions/publish-public-snapshot/core.mjs');const r=await handlePublication(request(),deps({...base,published_hash:'sensitive',data:{private:'no'}}));assert.equal(r.status,200);const body=await r.json();assert.equal(body.status,'synced');assert.equal(body.can_publish,false);assert.equal(body.automatic_interval_seconds,120);assert(!JSON.stringify(body).includes('sensitive'));assert(!('data' in body));assert.equal(r.headers.get('cache-control'),'no-store')});
test('saved public edits enable manual publish; pending or cooldown always disable',async()=>{const {handlePublication}=await import('../supabase/functions/publish-public-snapshot/core.mjs');for(const [extra,status,can] of [[{needs_publish:true},'dirty',true],[{needs_publish:true,pending_request_id:id,pending_status:'dispatch_unknown'},'dispatch_unknown',false],[{needs_publish:true,cooldown_until:'2099-01-01T00:00:00Z'},'cooldown',false]]){const r=await handlePublication(request(),deps({...base,...extra}));const b=await r.json();assert.equal(b.status,status);assert.equal(b.can_publish,can)}});
test('missing verification or RPC failure never becomes synced or enables publish',async()=>{const {handlePublication}=await import('../supabase/functions/publish-public-snapshot/core.mjs');for(const summary of [null,{...base,verified_hash_known:false}]){const r=await handlePublication(request(),deps(summary));assert.equal(r.status,503)}const d=deps(base);d.serviceClient.rpc=async()=>({data:null,error:{code:'failed'}});assert.equal((await handlePublication(request(),d)).status,503)});
test('state is readable without dispatch configuration but cannot enable publish',async()=>{const {handlePublication}=await import('../supabase/functions/publish-public-snapshot/core.mjs');const d=deps({...base,needs_publish:true});d.githubToken='';const b=await(await handlePublication(request(),d)).json();assert.equal(b.status,'not_configured');assert.equal(b.can_publish,false)});
test('manual stale-button unchanged reservation does not dispatch or create a second job',async()=>{const {executePublication}=await import('../supabase/functions/publish-public-snapshot/core.mjs');let calls=0;const r=await executePublication({action:'publish'},{environment:'test',githubToken:'placeholder',actorId:id,serviceClient:{rpc:async(name)=>{assert.equal(name,'reserve_public_snapshot');return {data:null,error:null}}},fetcher:async(url,options)=>{if(options?.method==='POST')calls++;return new Response(JSON.stringify(url.includes('release-manifest')?{schemaVersion:1,environment:'test',projectRef:'vppjcjfbcoxzofcuxmzz',sourceCommit:'a'.repeat(40),sourceTag:null}:{id:7}))}});assert.equal((await r.json()).status,'unchanged');assert.equal(calls,0)});
test('new SQL keeps summary service-only, checks hashes under shared lock and edits existing Test cron only',()=>{const sql=fs.readFileSync(require.resolve('../supabase/migrations/012_publication_state_and_two_minute.sql'),'utf8');assert.match(sql,/get_publication_status_summary/);assert.match(sql,/from public,anon,authenticated/);assert(sql.indexOf('pg_advisory_xact_lock(73491010)')<sql.indexOf('if published_hash=current_hash then return null'));assert.match(sql,/cron.alter_job/);assert.match(sql,/\*\/2 \* \* \* \*/);assert(!sql.includes('cron.schedule('));assert.match(sql,/project_ref='vppjcjfbcoxzofcuxmzz'/)});
